### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by petrovalex** [orgsync/react-list#105]
Hi,
I am using react list for rendering nested lists, so in itemRenderer function I am returning ReactList.
And the container which is hosting this nested list is my scrollParent. The problem is that in that case scrollTop method is not working property, as it does not take into account offset of the nested list relative to the scrollParent. 
What would be the best approach to fix that in your opinion?

**Comment by caseywebdev** [comment]
Please create a jsfiddle or codepen illustrating this issue.

**Comment by petrovalex** [comment]
[JsFiddle](https://jsfiddle.net/alexpetrov/3690cgf9/)

Expected behaviour is that it would scroll to root9.leaf4, but it scrolls to root0.leaf4. If in MyComponent you would replace ReactList with MyReactList, then it works as expected.

**Comment by caseywebdev** [comment]
It looks like this is a regression from #86

**Comment by caseywebdev** [comment]
I believe I've fixed this in my `fixed` branch. Please try out http://rawgit.com/orgsync/react-list/fixes/react-list.js and let me know. Also a note in your example, as the README states you aren't able to `scrollTo` an item that hasn't been rendered yet. Since you're using the `simple` render type in that example you're only getting the first `10` items rendered until the page is scrolled further. What you can do is use the `uniform` type or increase the `pageSize` prop.
