### ISSUE TITLE
Version 0.8.4 broke first render for type simple (and possibly others)

### ISSUE THREAD

**Issue by albertogasparin** [orgsync/react-list#165]
I think the changes you made on line 396, replacing:
```js
size = Math.max(size, pageSize);
```
with 
```js
if (type === 'uniform') size = Math.max(size, 1);
```
broke the first render for all other list types. This code now renders almost all the items at once: 

```js
<ReactList
  itemsRenderer={this.renderItemsContainer}
  itemRenderer={this.renderItem}
  length={items.length}
  type="simple"
  pageSize={8}
/>
```

While version 0.8.3 works as expected, rendering just 8 items on load.

**Comment by caseywebdev** [comment]
`simple` and `variable` lists seems to work as expected on the examples page. Can you provide a full example of the broken case?

**Comment by caseywebdev** [comment]
Does your `itemsRenderer` specify `overflow: auto` or `overflow: scroll` without a `height` or `max-height`?

**Comment by albertogasparin** [comment]
I've managed to replicate the issue here: https://jsfiddle.net/4cqqfmqd/
I've found the issue being related to the use of css animations (via `ReactCSSTransitionGroup`).
Basically, if the list items animate on enter with `height:0`, ReactList 0.8.4 tries to be too smart and renders nearly all the items. 
Moreover, setting `ReactCSSTransitionGroup.transitionAppear` option does not work probably due to ReactList managing the list (but that is not a big deal). 
Anyway, with ReactList 0.8.3 this behaviour was not happening, probably because `pageSize` was winning over the calculated amount of items that can fit in the initial view.

**Comment by albertogasparin** [comment]
Maybe a solution could be adding a new prop like `initialPageSize`, representing the initial amount of items that ReactList should be rendering. By default could be `0/null/undefined` (which means auto, keeping 0.8.4 behaviour), but once set it forces ReactList to render `n` amount of items on load.

**Comment by caseywebdev** [comment]
This isn't really an issue with the latest change, animating the along the same axis as the list just isn't supported right now. You'll notice that even with `0.8.3` everything may look fine initially, but as soon as you scroll to the threshold you'll get the entire rest of the list rendered. This is because `react-list` is depending on the size of the elements at render time to determine how many more elements should be rendered. In your case they're all starting at 0, which means `react-list` will render all of the items in an attempt to reach the end of the viewport.

A potential solution is specifying the animation transition time as a prop so `react-list` can defer calculating the element sizes until the animation period is over. I'm going to close this issue as the real problem is animation-specific. Feel free to open another issue or PR targeting support for same-axis animation/transition.
