### ISSUE TITLE
can not set initialIndex for variable hieght with no itemSizeGetter function defined 

### ISSUE THREAD

**Issue by nexus-uw** [orgsync/react-list#27]
Hi all,
when I try to create a list of chat messages and scroll to the bottom when the list is loaded 
using the following 
```jsx
<ReactList
  itemRenderer={this.itemRenderer}
  length={this.props.chats.length}
  itemsRenderer={this.itemsRenderer}
  variable={true}
  initialIndex={this.props.chats.length - 1}            
/> 
```
the list will not be initialized to the bottom but remain at the top. 

Drilling through the source, it seems that the getSizeOf function will return NaN if the itemSize has not been statically defined, no itemSizeGetter is defined, and the item's size has not already been calculated. This then causes getSpaceBefore to return 0, keeping the list scrolled to the top.

I am not sure if this by design or if it is a bug but if it is by design, could some message or error be generated when someone is using the same combination of properties as I am above?

Thanks,
Simon

**Comment by caseywebdev** [comment]
This is by design, because in your case the only way to scroll to the last item without a `itemSizeGetter` is to render the entire list. Alternatively, you could set `pageSize={this.props.chages.length}` and your example should work, at the expense of indeed rendering the entire list. Also you'll want to use `type='variable'` rather than `variable={true}`, I just noticed the README example is using the old API.
