### ISSUE TITLE
DOM growing in examples

### ISSUE THREAD

**Issue by vgoklani** [orgsync/react-list#29]
Hey, I was playing with your online examples, and it looks like your DOM elements are growing as I scroll. Does your library recycle the DOM elements?

Thanks,

Vishal

**Comment by caseywebdev** [comment]
The examples page needs some more descriptive text, I just haven't gotten to it yet. The lists that are type `simple` will grow in DOM elements as you scroll and that's by design. When you use the `variable` type with an `itemSizeGetter` or use the `uniform` type, DOM elements that are beyond the `threshold` will be recycled. Does that answer your question?
