### ISSUE TITLE
Allow passing in a className

### ISSUE THREAD

**Issue by Rob-ot** [orgsync/react-list#37]
Hello, this list view is great! Thanks for making it.

I'd like to be able to pass in a className to add a class to the root element of the ReactList. I could wrap it with a div and add the class to that but I'd rather not add a dom element just for that. Also other react modules I use allow this.

```
<ReactList className="animal-list" />
```

Thanks for considering!

**Comment by caseywebdev** [comment]
Have you looked at the `itemsRenderer` prop? It allows you to customize the wrapper around the list items.

**Comment by Rob-ot** [comment]
Right, that's useful but doesn't quite solve my problem.

Right now I see it creates 4 elements, the root element, the element that scrolls, the element that is transformed down as you scroll, and the items container(s).

My goal is to be able to to add a class to the root element that this creates, Right now my only option is to wrap it with another element which isn't the end of the world but it does complicate the JS and CSS related to it.

Modules like https://www.npmjs.com/react-tappable just pass the props they don't care about on to the root element they create.

**Comment by caseywebdev** [comment]
I have a couple problems with doing that.

First, the wrapper element doesn't even always exist. If you look at [the simple case](https://github.com/orgsync/react-list/blob/b9df86a81f3097767bce0604335142cd47e77a47/react-list.es6#L336), the only element that's returned is whatever `itemsRenderer` returns. There's a consistency in that you will always get at least `itemsRenderer`'s result, but the wrapper divs are only necessary in the `variable` and `uniform` cases.

Second, I don't particularly want to expose those wrappers to modification. Maybe it would be obvious to the developer or maybe not that their styling on that wrapper div could break the list functionality.

I've looked through some of our components using ReactList and we use a wrapper div to add class names. I think that's a fine pattern, especially because it ensures you don't have to worry about which list type you're using and you guarantee you won't be messing up any ReactList internal styling.

**Comment by Rob-ot** [comment]
That makes sense, thanks for the explanation.
