### ISSUE TITLE
Image grid loading issues

### ISSUE THREAD

**Issue by thornelius** [orgsync/react-list#40]
First of all, awesome job with this library!

I am encountering issues using ```react-list``` with an image grid. Whenever I set the ```react-list``` type to either ```variable``` or ```uniform``` the ```img``` elements are still preserving the old images from when I started the scroll. I understand why this is happening (because of the cache) but it looks very unusual. Can you think of anyway to resolve this, or even mitigate the image lag behavior? 

You can see a working example here (Just scroll down the page quickly and you can that the ```img``` elements do not update until I stop scrolling):

https://jsfiddle.net/thornelius/4Lz482dm/1/

Thanks!

**Comment by caseywebdev** [comment]
I've found that with `<img>` tags specifically, it's usually better to give them a unique key, therefore creating a new DOM element, rather than reusing the old one for this exact reason. In your example I simply changed `key={key}` to `key={index}` and the issue looks resolved.

https://jsfiddle.net/4Lz482dm/2/

**Comment by thornelius** [comment]
Sweet that worked great. Thanks for the help!

closing...
