### ISSUE TITLE
Support loading data on demand

### ISSUE THREAD

**Issue by nhantamdo** [orgsync/react-list#60]
My data is loaded on demand. Is there a hook to register the callback for more data when scrolling?
Thanks,

**Comment by caseywebdev** [comment]
See #24, it's up to you to decide when you should fetch new data and how. You can use `itemRenderer` as a gauge for what's being displayed, and you can use `getVisibleRange()` to get similar information on demand. ReactList won't tell you when to fetch more data because each use case is different. I recommend writing a component around ReactList that you can reuse for your use case and will handle your data loading needs.
